dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/IMG_20261008_093023.jpg"
