    - name: Generate Launcher Icons
      run: |
        flutter pub get
        dart run flutter_launcher_icons

    - name: Build Debug APK
      run: |
        flutter build apk --debug --no-tree-shake-icons
